### ISSUE TITLE
Add request body, URL, routing related functionalites

### ISSUE THREAD

**Issue by ryujumoto** [Ryuju0911/go_net_http_pkg#2]
## Background
I have implemented the basic functionalities such as listening to TCP connections, routing an incoming HTTP request to a registered handler, and handling it. However, there are many other functionalities HTTP servers should have.
 
## Goal
This issue will be closed when I implement the components described below.

### Overview
The current HTTP server cannot read request body, handle URL path properly, route requests to a handler efficiently, and resolve addresses.

### Todo
  - [x] Read request body
  - [x] Handle URL properly
  - [x] Do routing efficiently
  - [x] Resolve addresses
 
## Frequency
Weekly

## Deadline
2023/11

## References
[net/http source code](https://github.com/golang/go/tree/master/src/net/http)

## Notes
None

**Comment by ryujumoto** [comment]
## Work Time
14h

## Report
- I enabled the server to read request body, handle URL properly (wildcard, redirection, etc.), and do routing efficiently.
- Especially, efficient routing, which was added to Go just 3 months ago, was a challenging part. It builds a routing tree considering host, method, and wildcard. Then it provides the server with enhanced routing. [The issue](https://github.com/golang/go/issues/61410) describes the details.

## References
None

## Notes
None

**Comment by ryujumoto** [comment]
## Work Time
6h

## Report
- I have introduced an address resolver to the package. The address resolution process consists of three stages: checking the Host file (/etc/hosts), examining the DNS cache, and querying DNS servers for answers. The latter two parts are too complicated, so I skipped implementing the functionalities for now.

## References
None

## Notes
None
